Fix potential NPE
salesforce/dockerfile-image-update pull request #192
Opened 2021-01-26 09:34 UTC by stephenc

A noddy NPE that my IDE was complaining about

2021-01-26 15:59 UTC, afalko commented on dockerfile-image-update/src/main/java/com/salesforce/dockerfileimageupdate/utils/DockerfileGitHubUtil.java
> +        if (tree != null) {
Put this check before the break above, that way we retry and error if this stays null

2021-01-26 16:00 UTC, afalko requested changes
Move null check to retry loop

2021-01-26 16:21 UTC, afalko approved these changes

2021-01-28 18:06 UTC, justinharringa approved these changes

2021-01-28 18:06 UTC, merged