Refactor all command
salesforce/dockerfile-image-update pull request #301
Opened 2022-01-27 01:13 UTC by avimanyum

This PR refactors the code for the All subcommand and makes it consistent with the way the parent subcommand works by utilizing similar set of underlying classes. This PR will also take care of the following git issues:
https://github.com/salesforce/dockerfile-image-update/issues/72
https://github.com/salesforce/dockerfile-image-update/issues/149

2022-01-27 15:34 UTC, afalko commented on dockerfile-image-update/src/main/java/com/salesforce/dockerfileimageupdate/subcommands/commonsteps/Common.java
> +    public void prepareToCreatePullRequests(final Namespace ns,
Let's move this to `util` and name the class `PullRequests` and the method would be `prepareToCreate`. 

The callers would look like: `new PullRequests().prepareToCreate(...)`

Note that if we were to do it all over again, we wouldn't name anything `util`, but that is something we'd fix in a later refactoring.

2022-01-27 15:36 UTC, afalko requested changes
Looks great! Just a few naming and style requests

2022-01-27 18:12 UTC, avimanyum commented on dockerfile-image-update/src/test/java/com/salesforce/dockerfileimageupdate/subcommands/impl/ParentTest.java
> +        Mockito.verify(parent, times(0)).getGitForkBranch(ns);
I am importing import static org.mockito.Matchers.*; - is there something different you had in mind?

2022-01-27 22:20 UTC, afalko commented on dockerfile-image-update/src/test/java/com/salesforce/dockerfileimageupdate/subcommands/impl/ParentTest.java
> +        Mockito.verify(parent, times(1)).getGitForkBranch(ns);
still see non-static import

2022-01-27 22:22 UTC, afalko commented on dockerfile-image-update/src/test/java/com/salesforce/dockerfileimageupdate/subcommands/impl/ParentTest.java
> +        Mockito.verify(parent, times(0)).getGitForkBranch(ns);
It would be org.mockito.* 

Intellij will do it automatically for you

2022-01-27 22:23 UTC, afalko commented on dockerfile-image-update/src/test/java/com/salesforce/dockerfileimageupdate/subcommands/impl/ParentTest.java
> +        Mockito.verify(parent, times(0)).getGitForkBranch(ns);
You do it right here: https://github.com/salesforce/dockerfile-image-update/pull/301/files#diff-625d7e7e19ef76fd41b6ff92795a45c55dbbb9e956d42237321688171bb8afb5R15

2022-01-28 19:32 UTC, afalko approved these changes

2022-01-28 20:53 UTC, merged